name: Build GD GPT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android64:
    name: Build GD GPT for Android 64-bit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build GD GPT
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          sdk: "5.8.2"
          cli: latest

      - name: Upload GD GPT
        uses: actions/upload-artifact@v4
        with:
          name: GD-GPT-Android64
          path: ${{ steps.build.outputs.build-output }}
